repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11 # Use the latest version of Ruff
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^todo\.yaml$
      - id: ruff-format
        exclude: ^todo\.yaml$
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: ./.venv/bin/pytest
        language: system
        types: [python]
        pass_filenames: false
      - id: behave
        name: behave
        entry: ./.venv/bin/behave
        language: system
        types: [python]
        pass_filenames: false
